### ISSUE TITLE
Asynchronous load of google maps API

### ISSUE THREAD

**Issue by Masadow** [kuhnza/angular-google-places-autocomplete#10]
It would be a good improvement if this plugin could integrates well with angular-google-maps plugin.

I would like to broadcast an event to this plugin when google maps is loaded.

**Comment by kuhnza** [comment]
Sorry @Masadow probably not going to happen. I don't wan't to complicate the lib with hidden initialisation steps. 

Of course if this is a major issue for lots of people and someone wants write something that makes it completely transparent for ordinary use cases then I'd be willing to consider it.
