### ISSUE TITLE
Can i select only cities around the worlds.

### ISSUE THREAD

**Issue by dilip-borad** [kuhnza/angular-google-places-autocomplete#11]
http://plnkr.co/edit/il2J8qOI2Dr7Ik1KHRm8?p=preview

Please check the second example of this plnkr.
I need to set up specific country wise city or all cities around the world.

Help me

**Comment by kuhnza** [comment]
@dilip-borad the example you've provided is using a different autocomplete directive to this. 

Still I'd suggest you check out the API spec for the relevant options: https://developers.google.com/maps/documentation/javascript/reference#AutocompletionRequest
