### ISSUE TITLE
doesn't works anymore

### ISSUE THREAD

**Issue by TuNi54** [kuhnza/angular-google-places-autocomplete#124]
Hi, 

Since few hours, it doesn't works anymore. Input is hidden ..

Someone else ?

Thanks

**Comment by itsHowlingWolf** [comment]
Same issue here!

**Comment by TuNi54** [comment]
@kuhnza we need you :)

**Comment by harrisonlingard** [comment]
Not working for me either - my apps are down :(

**Comment by martincrb** [comment]
Same here, the input is hiding with a display: none, anybody knows a workaround to make it visible? it works if i inspec and display it!

**Comment by dagthomas** [comment]
Just add a class/id to the input and do "display:initial!important" and it will work, atleast.

**Comment by ThomasFlorelli** [comment]
`input[g-places-autocomplete] { display:initial!important }` indeed does the job but please keep us posted

**Comment by trippo** [comment]
i think is the file control.js that hide the input field, if you block this on network tab you can see the input... but nothing autocomplete work

**Comment by jpescada** [comment]
There are a few methods on [util.js](https://maps.googleapis.com/maps-api-v3/api/js/32/5/intl/en_gb/util.js) that trigger `display: none`. _Might_ be related with this issue.

**Comment by 312c** [comment]
The first time the `_.ZA` function is called in util.js is when the fields are being hidden.  Which is being called from a method in [places_impl.js](https://maps.googleapis.com/maps-api-v3/api/js/32/5/places_impl.js) that looks like `_.ZA(a.b, !!a.get("attributionText") && !a.get("hide"))`.

**Comment by MatMc** [comment]
The first time the `_.ZA` function is called in util.js is when the fields are being hidden.  Which is being called from a method in [places_impl.js](https://maps.googleapis.com/maps-api-v3/api/js/32/5/places_impl.js) that looks like `_.ZA(a.b, !!a.get("attributionText") && !a.get("hide"))`.

**Comment by wal-yaseen** [comment]
changing the version to 3.30 fixes it for me
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&v=3.30libraries=places"></script>

**Comment by MatMc** [comment]
I can confirm that changing the version to 3.31 is a viable workaround, the method call in my comment above was added in 3.32

**Comment by krispy1298** [comment]
After trying to debug this on a site, I found that the new [Places Service for 3.32](https://developers.google.com/maps/documentation/javascript/reference/3.exp/places-service#PlacesService) has a required param. It needs to be passed a div element to inject the Google attribution text/logo.

**Comment by renjuramachandran** [comment]
We were also facing the same issue for two days. But yesterday it seems to be fixed.

**Comment by TuNi54** [comment]
it seems to be fixed !

**Comment by chethannad** [comment]
It looks fixed but my client so serious on this issue and they requested an explanation and recommendations to monitor in future regarding this issue. 
Please explain to me why we had this issue from google API

Thanks in advance

**Comment by MatMc** [comment]
@chethannad this was caused by an update to Google's experimental version of the Places Service.  Turns out that by default if you do not specify an API version you get the non-stable/non-release version (???) of the API.  Specifying `v3` when loading the API guarantees the latest stable version, while specifying `v3.xx` gets whatever sub-version you want.  In this case 3.31 is the current release build and did not have this issue, but anyone who did not specify a version received 3.32 which is currently under development.

**Comment by chethannad** [comment]
Thank you @MatMc

**Comment by kuhnza** [comment]
Hi everyone, sorry to hear this issue has caused a bit of grief. As you can probably tell by the commit history that I haven't had any significant input into this lib for years now. I no longer have the need, time or desire to maintain it. 

I'd happily hand over to anyone who wishes to take it on. If you're interested please let me know. Until such time as someone take it on you should treat this library as deprecated.

**Comment by goneale** [comment]
It does seem to be fixed without specifying a `v` parameter now, but it is a bit scary to leave it open-ended without one if the latest version is directing to experimental builds. If I see this problem happen one more time, I think I'll introduce the `v` parameter too. Thanks for the investigation @chethannad @wal-yaseen
