### ISSUE TITLE
Issue with enabling force-selection clearing input

### ISSUE THREAD

**Issue by mliu95** [kuhnza/angular-google-places-autocomplete#13]
When I enable force-selection on an input in a bootstrap modal, clicking outside of the autocomplete container autoselects an address for the user, which works fine. However, when I select an address, the input is populated with the information and I still have focus on the input. Losing focus of the input clears it, which is problematic.

For those trying to reproduce this bug, I'm on the most recent version. Here's my code:

HTML

    <form class="form-horizontal" name="propertyForm" ng-submit="propertyForm.$valid && submitProperty()">
      <div class="modal-body">
        <div class="form-group" ng-class="{ 'has-error': propertyForm.address.$invalid && propertyForm.address.$dirty }">
          <label class="control-label col-md-3">
            Address
          </label>
          <div class="col-md-9">
            <input type="text" name="address" class="form-control" placeholder="1234 W 9th St" ng-model="address" g-places-autocomplete force-selection="true" options="options" required>
          </div>
        </div>
  </div>
</form>

My options object

    $scope.options = {
      componentRestrictions: { country: 'us' },
      types: ['geocode']
    };

I have an event listener on the `g-places-autocomplete:select` event as well and it correctly fires.

**Comment by tamonan** [comment]
Same problem. Input field is cleared on focus lost

**Comment by jamhall** [comment]
Has this been resolved? Thanks

**Comment by mliu95** [comment]
Don't believe so. Still getting the error and the last commit was 10 days before my question was posted. I've since reverted to a previous working build.

**Comment by jamhall** [comment]
Ok, thank you for the information.

**Comment by ankitg06** [comment]
@mliu95 which working build did you revert to?  I'm facing the same issue.

**Comment by mliu95** [comment]
@ankitg06 https://github.com/kuhnza/angular-google-places-autocomplete/commit/2f3856f36fe3bcf67d647a152c4a4d1748ebffdc This commit appears to have broken things, I'd revert to the commit before it

**Comment by varunagg45** [comment]
I am having the same issue. When can this be resolved?

**Comment by davecyen** [comment]
+1

**Comment by kijanawoodard** [comment]
Was going to report this issue. 

Any ETA on bower package push?

**Comment by rweng** [comment]
+1, reverting to 586479ed091a8900a81eb378460eafe40c2633c7 works

**Comment by mliu95** [comment]
PR #18 fixes this issue for me.
