### ISSUE TITLE
Can you add some documentation for hooking into the events :)

### ISSUE THREAD

**Issue by jimmyt1988** [kuhnza/angular-google-places-autocomplete#21]
How do i listen to the on selected event ? (for example, to get the Lat and Lng of the selected location?)

**Comment by cjonasw** [comment]
Give this a go on the scope of the directive.

```
$scope.$on 'g-places-autocomplete:select', (event) ->
    # Do stuff
    console.log event
```

**Comment by jimmyt1988** [comment]
Yes thank you!


    $scope.$on( 'g-places-autocomplete:select', function(event) {
        console.log(event);
        $scope.Lat.Value = event.targetScope.model.geometry.location.D;
        $scope.Lng.Value = event.targetScope.model.geometry.location.k;
    });

**Comment by nanuuki** [comment]
Nice! Note that you should use the `location.lat()` and `location.lng()` methods instead of accessing `location.D` and `location.k` directly (https://developers.google.com/maps/documentation/javascript/3.18/reference#LatLng);

```javascript
$scope.$on( 'g-places-autocomplete:select', function (event) {
    console.log(event);
    $scope.Lat.Value = event.targetScope.model.geometry.location.lat();
    $scope.Lng.Value = event.targetScope.model.geometry.location.lng();
});

**Comment by nanuuki** [comment]
A slightly cleaner way to access the place data:

```javascript
$scope.$on('g-places-autocomplete:select', function (event, data) {
  console.log('Event', event);
  console.log('Place data', data);
  console.log('Geometry', data.geometry.location.lat(), data.geometry.location.lng());
});
```
This way you don't have to fiddle with `event.targetScope.model` :)
