### ISSUE TITLE
Capturing data on completed search

### ISSUE THREAD

**Issue by quipu** [kuhnza/angular-google-places-autocomplete#3]
Hi @kuhnza. Thanks for the nice directive - just what I'm looking for. I'm just having a few problems figuring out how to capture the data from a search.

I've posted a question on SO - if you have time to have a look at it I'd really appreciate it.

http://stackoverflow.com/questions/26233748/capturing-changes-to-model-using-angular-google-places-autocomplete

Thanks!

**Comment by ivan-ivakic** [comment]
It should be as simple as: http://stackoverflow.com/a/27980168/4460884

**Comment by quipu** [comment]
I switched to customising https://github.com/israelidanny/ion-google-place - see my PR for that project for changes to make work with Google Places rather than the Geocoding service.

**Comment by kuhnza** [comment]
Thanks @ivan-ivakic that's the right way to do it.

**Comment by claudevandort** [comment]
I couldn't get the search results using @ivan-ivakic solution, so (even if it's kind of ugly) I had to `new_place = JSON.parse($filter('json')($scope.place));` the results.

Hope it helps 😀
