### ISSUE TITLE
weird positioning issue

### ISSUE THREAD

**Issue by bautistaI** [kuhnza/angular-google-places-autocomplete#4]
the location of the suggested results displays very far from the input field. I'm using bootstrap to style my form, and nothing else. 
![screen shot 2014-11-11 at 12 59 47 pm](https://cloud.githubusercontent.com/assets/1901094/4998959/ffded810-69a2-11e4-80e0-ea24f3579f2f.png)

**Comment by kuhnza** [comment]
Thanks for the investigation @davemoore24. Did you experience any issues when scrolling after reverting to 0.1.4?

**Comment by billewatts** [comment]
Same issue. It was being caused by an element above the directive that was hidden with ng-show .. for some reason throwing off the calc of top, I think.

**Comment by samuelcastro** [comment]
+1 Some issue here.

**Comment by jimmyt1988** [comment]
Same issue here :)

**Comment by davemoore24** [comment]
No issues reported

**Comment by jimmyt1988** [comment]
In that case, any ideas what i'm doing wrong? It works in chrome, ie11, firefox, android, iphone but not windows phone. I was wondering if you might have an idea what might be going wrong?

**Comment by maksbd19** [comment]
I am having the same issue. My case is I have some "steps" in my form and I paginated using ng-if directive. Geocomplete input elements are in the second step of the form. Now when I go to step 2 and type in the input box it shows the suggestion box a little down, where that element would go if I didn't have any conditional rendering using ng-if.

**Comment by alexfdz** [comment]
I've faced the same issue due the position calculation is done before the page is fully rendered, so the resolved position is not the correct one.

The problem is that the position refresh is only executed once:

```javascript
$scope.$watch('predictions', function () {
                    $scope.position = getDrawerPosition($scope.input);
                });
```

Changed the clearPredictions function to trigger the watcher

```javascript
function clearPredictions() {
                        $scope.active = -1;
                        $scope.selected = -1;
                        $scope.predictions = [];
                    }
```

Change added to pull request #26

**Comment by ankitg06** [comment]
@alexfdz Thanks for your solution.  It works great except in the case where the predictions dropdown is being displayed while the window width is changed.  Any ideas for how to resolve without adding a window resize listener?

**Comment by alexfdz** [comment]
@ankitg06 the clearPredictions method is called several times for different events, like every single time that the predictions are requested ([autocomplete.js#L193](blob/master/src/autocomplete.js#L193)).

So if you resize the window, and continue the search, the dropdown should relocate. If you need to relocate the dropdown while the window is resizing, you would need to add the window resize listener.

**Comment by z-SPaRk** [comment]
Had same problem on android, was html{height: 100%} needed min-height: 100% 
bug fixed
