### ISSUE TITLE
how to add two inputs with g-places-autocomplete?

### ISSUE THREAD

**Issue by patrioticcow** [kuhnza/angular-google-places-autocomplete#40]
i have 

`<input class="width100" type="text"placeholder="Location" data-force-selection="true" data-ng-value="details.address" data-ng-model="details.address" data-g-places-autocomplete>`

and

`<input class="width100" type="text"placeholder="Location" data-force-selection="true" data-ng-value="details.address" data-ng-model="details.search_location" data-g-places-autocomplete>`

but the `this.$parent` value from both are the same.

ideas?

**Comment by ayushishah-easternts** [comment]
Hi,

any idea how to proceed on this ?
