### ISSUE TITLE
dropdown result positioning issue

### ISSUE THREAD

**Issue by jaxox** [kuhnza/angular-google-places-autocomplete#6]
It looks good on my laptop browser but when i push the app to my android phone, the position is weird. I am using ionic and cordova. 

 
![screenshot_2014-12-09-00-33-01](https://cloud.githubusercontent.com/assets/1198637/5354294/e44329a0-7f3a-11e4-9294-3c35141baacf.png)

**Comment by mliu95** [comment]
Did you ever find a workaround/fix for this?

**Comment by kuhnza** [comment]
Marking as duplicate of #4
